### PR TITLE
Updated to 1.13.2 spigot. Needs client mod update.

### PR DESCRIPTION
**Pull request by Webbeh**
Please see https://github.com/DaFlight/DaFlightManager/issues/2 for informations.

### CODE REVIEW

**Comment by dags-** [comment]
Awesome, thanks!

**Comment by Webbeh** [comment]
As stated in the title, the client-side mod will need an update to use the same channels.

The registration seems to work (there's no error shown at any point and I receive the "Player xxx has been registered" message on the server), but the max fly speed isn't sent to the client. Or the client just ignores it, I don't know, I have no experience in client-side modding.

**Comment by dags-** [comment]
DaFlight client should already be using those channels as this change was required as part of the 1.12-1.3 update:
https://github.com/DaFlight/DaFlight/blob/master/src/main/java/me/dags/daflight/handler/MessageHandler.java

Will look into it if it's not working as-is

**Comment by Webbeh** [comment]
What's the expected behaviour ? For now, I see no difference between singleplayer and multiplayer with daflightmanager. 

Also is there a way to remove that annoying speed limit when fly boosting ? I was used to have a boost of 100, now I'm limited to 20. My server can handle it... It would just be nice to simply allow direct input of the limit, on top of the slider.

EDIT: is it possible that the ResourceLocation adds an extra symbols to the namespace ? Or to the channel name ? Would be weird that the "connect" channel works but not the others...

**Pull request merged**
